---

- name: Create the bash extensions directory
  file:
    dest: ~/.bash.d/
    state: directory

- name: Create the user binaries directory
  file:
    dest: ~/.bash.d/bin/
    state: directory

- name: Copy standard utilities
  copy:
    src: files/bin/
    dest: ~/.bash.d/bin/
    mode: u+rwx

- name: Setup .bashrc
  copy:
    src: files/bashrc
    dest: ~/.bashrc

- name: Setup .bash_profile
  copy:
    src: files/bash_profile
    dest: ~/.bash_profile
