---
- name: Clone the bash dotfiles repository
  git: repo=https://andres-arana@github.com/andres-arana/dotfiles-bash.git dest=~/.bash

- name: Create the bash directory
  file: dest=~/.bash.d/ state=directory

- name: Create the user binaries directory
  file: dest=~/Binaries state=directory

- name: Link bashrc to the cloned versions
  file: src=~/.bash/bashrc.sh dest=~/.bashrc state=link force=yes

- name: Link bashprofile to the cloned versions
  file: src=~/.bash/bashprofile.sh dest=~/.bash_profile state=link force=yes

- name: Link bashprompt to the cloned versions
  file: src=~/.bash/bashprompt.sh dest=~/.bash.d/prompt.bash state=link force=yes
