---
- name: Install starship prompt
  ansible.builtin.apt:
    name: starship
    state: latest
  become: true

- name: Create the bash extensions directory
  ansible.builtin.file:
    dest: ~/.bash.d/
    state: directory
    mode: '0755'

- name: Create the user binaries directory
  ansible.builtin.file:
    dest: ~/.bash.d/bin/
    state: directory
    mode: '0755'

- name: Setup .bashrc
  ansible.builtin.copy:
    src: files/bashrc
    dest: ~/.bashrc
    mode: '0644'

- name: Setup .bash_profile
  ansible.builtin.copy:
    src: files/bash_profile
    dest: ~/.bash_profile
    mode: '0644'
