---
- name: Install cURL for API http request making
  ansible.builtin.apt:
    name: curl
    state: latest
  become: true

- name: Install tree for better directory listing
  ansible.builtin.apt:
    name: tree
    state: latest
  become: true

- name: Install htop for process management
  ansible.builtin.apt:
    name: htop
    state: latest
  become: true

- name: Install bat for syntax-aware file displays
  ansible.builtin.apt:
    name: bat
    state: latest
  become: true

- name: Install eza for better directory listings
  ansible.builtin.apt:
    name: eza
    state: latest
  become: true

- name: Install archive managers
  ansible.builtin.apt:
    name:
      - unace
      - unrar
      - zip
      - unzip
      - p7zip-full
      - p7zip-rar
      - sharutils
      - rar
      - uudeview
      - mpack
      - arj
      - cabextract
      - file-roller
    state: latest
  become: true
