---
  - name: Check if vagrant is installed
    command: dpkg -s vagrant
    ignore_errors: true
    register: vagrant_installed

  - name: Download the vagrant installer
    get_url: url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb dest=/tmp/vagrant.deb
    when: vagrant_installed.rc != 0

  - name: Install the vagrant package
    apt: deb=/tmp/vagrant.deb
    sudo: yes
    when: vagrant_installed.rc != 0

  - name: Clone the vagrant dotfiles and utility scripts
    git: repo=https://andres-arana@github.com/andres-arana/dotfiles-vagrant.git dest=~/.vagrant

  - name: Link the invm script to the local binaries
    file: src=~/.vagrant/invm dest=~/Binaries/invm state=link force=yes

  - name: Link the invmf script to the local binaries
    file: src=~/.vagrant/invmf dest=~/Binaries/invmf state=link force=yes
