---
  - name: Check if vagrant is installed
    command: dpkg -s vagrant
    ignore_errors: true
    register: vagrant_installed

  - name: Download the vagrant installer
    get_url: url=https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb dest=/tmp/vagrant.deb
    when: vagrant_installed.rc != 0

  - name: Install the vagrant package
    apt: deb=/tmp/vagrant.deb
    become: yes
    when: vagrant_installed.rc != 0

  - name: Install vagrant commandline completion
    get_url: url=https://raw.github.com/kura/vagrant-bash-completion/master/etc/bash_completion.d/vagrant dest=/etc/bash_completion.d/vagrant
    become: yes

  - name: Add virtualbox secure apt key
    apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc
    become: yes

  - name: Add virtualbox repository to apt sources
    apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian wily contrib"
    become: yes

  - name: Install DKMS to ensure virtualization kernel is mantained
    apt: name=dkms state=present
    become: yes

  - name: Install virtualbox
    apt: name=virtualbox-5.0 state=latest
    become: yes

  - name: Clone the vagrant dotfiles and utility scripts
    git: repo=https://andres-arana@github.com/andres-arana/dotfiles-vagrant.git dest=~/.vagrant

  - name: Link the invm script to the local binaries
    file: src=~/.vagrant/invm dest=~/Binaries/invm state=link force=yes

