# Install Node.js using packages crafted by NodeSource
---
- name: Install HTTPS transport for APT
  apt:
    name: apt-transport-https
    state: latest
  become: yes

- name: Import the NodeSource GPG key into apt
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  become: yes

- name: Add NodeSource deb repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_9.x {{ ansible_distribution_release }} main'
    state: present
  become: yes

- name: Add NodeSource deb-src repository
  apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_9.x {{ ansible_distribution_release }} main'
    state: present
  become: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: latest
  become: yes
