# Install Node.js using packages crafted by NodeSource
---
- name: Add the nodesource repository
  ansible.builtin.deb822_repository:
    name: nodejs
    types: deb
    uris: https://deb.nodesource.com/node_22.x
    suites: nodistro
    components: main
    architectures: amd64
    signed_by: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
  become: true

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: latest
    update_cache: true
  become: true
