# Install Node.js using packages crafted by NodeSource
---
- name: Add the nodesource repository
  deb822_repository:
    name: nodejs
    types: deb
    uris: https://deb.nodesource.com/node_22.x
    suites: nodistro
    components: main
    architectures: amd64
    signed_by: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
  become: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: latest
  become: yes
