# Install Node.js using packages crafted by NodeSource
---
- name: Install HTTPS transport for APT
  apt:
    name: apt-transport-https
    state: latest
  become: yes

- name: Import the NodeSource GPG key into apt
  get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    dest: /etc/apt/keyrings/nodesource.asc
    mode: '0644'
  become: yes

- name: Add NodeSource deb repository
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_20.x jammy main'
    filename: 'nodejs'
    state: present
  become: yes

- name: Add NodeSource deb-src repository
  apt_repository:
    repo: 'deb-src [signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_20.x jammy main'
    filename: 'nodejs'
    state: present
  become: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: latest
  become: yes
