
[cursor.style]
blinking = "Always"
shape    = "Block"

[font]
size = 10

[font.normal]
family = "Inconsolata Nerd Font Mono"
style  = "Regular"

[terminal.shell]
program = "tmux"

[window]
decorations  = "none"
opacity      = 1
startup_mode = "Maximized"

[general]
live_config_reload = true
import             = ["~/.config/alacritty/gruvbox_dark.toml"]

[env]
TERM = "alacritty"

[[keyboard.bindings]]
key   = "Return"
mods  = "Shift"
chars = "\u001B\r"
