#!/usr/bin/env bash

################################################################################
# Paths and settings
################################################################################
VIM_CONFIG_FILE=$HOME/.vimrc
TERMINAL_CONFIG_FILE=$HOME/.config/xfce4/terminal/terminalrc
TERMINAL_USER_THEMES_FOLDER=${HOME}/.local/share/xfce4/terminal/colorschemes/
TERMINAL_SYSTEM_THEMES_FOLDER=/usr/share/xfce4/terminal/colorschemes/

################################################################################
# Toggle the current theme variant
################################################################################
# Try to get which is the active theme from vimrc
CURRENT_VARIANT=$(cat $VIM_CONFIG_FILE | grep "set background" | cut -d"=" -f 2)
if [[ "$CURRENT_VARIANT" == "dark" ]]; then
  TARGET_VARIANT="light"
else
  TARGET_VARIANT="dark"
fi

#VIM_BACKGROUND=$VARIANT

################################################################################
# Change the terminal config
################################################################################
# Set the target theme
TERMINAL_THEME=gruvbox-$TARGET_VARIANT

# Check if the theme file exists
TERMINAL_THEME_PATH="${TERMINAL_USER_THEMES_FOLDER}${TERMINAL_THEME}.theme"
if [ -f "$TERMINAL_THEME_PATH" ]; then
  TERMINAL_THEME_FILE=$TERMINAL_THEME_PATH
else
  TERMINAL_THEME_PATH="${TERMINAL_SYSTEM_THEMES_FOLDER}${TERMINAL_THEME}.theme"
  if [ -f  "$TERMINAL_THEME_PATH" ]; then
    TERMINAL_THEME_FILE=$TERMINAL_THEME_PATH
  else
    echo "Unable to find theme $TERMINAL_THEME in themes directories"
    exit 1
  fi
fi

FOREGROUND=$(cat $TERMINAL_THEME_FILE | grep ColorForeground)
BACKGROUND=$(cat $TERMINAL_THEME_FILE | grep ColorBackground)
PALETTE=$(cat $TERMINAL_THEME_FILE | grep ColorPalette)

sed \
  -i'' \
  -e "s/ColorForeground.*/${FOREGROUND}/" \
  -e "s/ColorBackground.*/${BACKGROUND}/" \
  -e "s/ColorPalette.*/${PALETTE}/" \
  ${TERMINAL_CONFIG_FILE}

#################################################################################
## Vim
#################################################################################
sed \
  -i'' \
  -e "s/background=.*/background=$TARGET_VARIANT/" \
  $VIM_CONFIG_FILE

