#!/usr/bin/env bash

# Arguments
THEME=$1

# Local variables
CONFIG_FILE=$HOME/.config/xfce4/terminal/terminalrc

# Check if the theme exists in the user's directory
THEME_PATH="${HOME}/.local/share/xfce4/terminal/colorschemes/${THEME}.theme"
if [ -f "$THEME_PATH" ]; then
  THEME_FILE=$THEME_PATH
else
  THEME_PATH="/usr/share/xfce4/terminal/colorschemes/${THEME}.theme"
  if [ -f  "$THEME_PATH" ]; then
    THEME_FILE=$THEME_PATH
  else
    echo "Unable to find theme $THEME in themes directories"
    exit 1
  fi
fi

NAME=$(cat $THEME_FILE | grep Name)
FOREGROUND=$(cat $THEME_FILE | grep ColorForeground)
BACKGROUND=$(cat $THEME_FILE | grep ColorBackground)
PALETTE=$(cat $THEME_FILE | grep ColorPalette)

echo "Modified file:"
cat $CONFIG_FILE > ~/.bash.d/bin/input.txt
cat $CONFIG_FILE | sed "s/ColorForeground.*/${FOREGROUND}/" | sed "s/ColorBackground.*/${BACKGROUND}/" | sed "s/ColorPalette.*/${PALETTE}/" > ${CONFIG_FILE}.new
mv ${CONFIG_FILE}.new $CONFIG_FILE

