---
- name: Clone the FZF repository
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf

- name: Install FZF
  command: ~/.fzf/install --no-update-rc

- name: Setup the FZF initializer script
  copy:
    content: "[ -f ~/.fzf.bash ] && source ~/.fzf.bash"
    dest: ~/.bash.d/fzf.bash

