---
- name: Install fzf and bat for the preview window
  ansible.builtin.apt:
    name:
      - fzf
      - bat
    state: latest
  become: true

- name: Install the fzf initializer
  ansible.builtin.copy:
    src: files/fzf.bash
    dest: ~/.bash.d/fzf.bash
    force: true
    mode: '0644'

- name: Install fzf-git keybindings
  ansible.builtin.copy:
    src: files/fzf-git.sh
    dest: ~/.bash.d/fzf-git.bash
    force: true
    mode: '0644'
