---
- name: Install git related software
  apt:
    name: 
      - tig
      - git
    state: latest
  become: yes

- name: Setup .gitconfig
  copy:
    src: files/gitconfig
    dest: ~/.gitconfig

- name: Setup .gitignore
  copy:
    src: files/gitignore
    dest: ~/.gitignore
