---
- name: Add the github cli repository
  ansible.builtin.deb822_repository:
    name: github-cli
    types: deb
    uris: https://cli.github.com/packages
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://cli.github.com/packages/githubcli-archive-keyring.gpg
  become: true

- name: Install git related software
  ansible.builtin.apt:
    name:
      - tig
      - git
      - gh
    state: latest
    update_cache: true
  become: true

- name: Setup .gitconfig
  ansible.builtin.copy:
    src: files/gitconfig
    dest: ~/.gitconfig
    mode: '0644'

- name: Setup .gitignore
  ansible.builtin.copy:
    src: files/gitignore
    dest: ~/.gitignore
    mode: '0644'

- name: Install gh shell completions
  ansible.builtin.copy:
    src: files/gh-completion.bash
    dest: ~/.bash.d/gh-completion.bash
    force: true
    mode: '0644'
