---
- name: Add the google cloud sdk repository
  ansible.builtin.deb822_repository:
    name: google-cloud-sdk
    types: deb
    uris: https://packages.cloud.google.com/apt
    suites: cloud-sdk
    components: main
    architectures: amd64
    signed_by: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  become: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - google-cloud-sdk
      - kubectl
    state: latest
    update_cache: true
  become: true

- name: Install the kubectl bash completion
  ansible.builtin.copy:
    content: "source <(kubectl completion bash)"
    dest: ~/.bash.d/kubectl.bash
    force: true
    mode: '0644'
