---

- name: Import the google cloud sdk key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/keyrings/google-cloud.gpg
    mode: '0644'
  become: yes

- name: Add google cloud sdk  deb repository
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/google-cloud.gpg] http://packages.cloud.google.com/apt cloud-sdk main'
    filename: 'gcloud'
    state: present
  become: yes

- name: Install required packages
  apt:
    name:
      - google-cloud-sdk
      - kubectl
    state: latest
  become: yes

- name: Install the kubectl bash completion
  copy:
    content: "source <(kubectl completion bash)"
    dest: ~/.bash.d/kubectl.bash
    force: yes
