---
- name: Add the google cloud sdk repository
  deb822_repository:
    name: google-cloud-sdk
    types: deb
    uris: http://packages.cloud.google.com/apt
    suites: cloud-sdk
    components: main
    architectures: amd64
    signed_by: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  become: yes

- name: Install required packages
  apt:
    name:
      - google-cloud-sdk
      - kubectl
    state: latest
  become: yes

- name: Install the kubectl bash completion
  copy:
    content: "source <(kubectl completion bash)"
    dest: ~/.bash.d/kubectl.bash
    force: yes
