---
- name: Install xclip for clipboard management
  apt:
    name: xclip
    state: latest
  become: yes

- name: Install tmux itself
  apt:
    name: tmux
    state: latest
  become: yes

- name: Setup .tmux.conf
  copy:
    src: files/tmux.conf
    dest: ~/.tmux.conf

- name: Setup dark theme
  copy:
    src: files/tmux-gruvbox-dark.conf
    dest: ~/.tmux/

- name: Setup light theme
  copy:
    src: files/tmux-gruvbox-light.conf
    dest: ~/.tmux/

