---
- name: Install xclip for clipboard management
  apt: name=xclip state=latest
  become: yes

- name: Install tmux itself
  apt: name=tmux state=latest
  become: yes

- name: Setup TPM
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

- name: Setup .tmux.conf
  copy: src=files/tmux.conf dest=~/.tmux.conf
