---
- name: Install tmux and xclip for clipboard management
  ansible.builtin.apt:
    name:
      - tmux
      - xclip
    state: latest
  become: true

- name: Setup .tmux.conf
  ansible.builtin.copy:
    src: files/tmux.conf
    dest: ~/.tmux.conf
    mode: '0644'

- name: Install TPM
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    version: master
