---
- name: Install xclip for clipboard management
  apt:
    name: xclip
    state: latest
  become: yes

- name: Install tmux itself
  apt:
    name: tmux
    state: latest
  become: yes

- name: Setup .tmux.conf
  copy:
    src: files/tmux.conf
    dest: ~/.tmux.conf

- name: Setup theme.conf
  copy:
    src: files/theme.conf
    dest: ~/.tmux/theme.conf

