---

- name: Ensure APT https transport is available
  apt: name={{item}} state=latest
  become: yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Ensure docker apt key is available
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  become: yes

- name: Ensure docker repository is available
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-xenial main" filename="docker"
  become: yes

- name: Ensure docker is installed
  apt: name=docker-engine state=latest
  become: yes
