---
- name: Import the docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add the docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    filename: 'docker'
    state: present
  become: yes

- name: Ensure docker is installed
  apt:
    name: docker-ce
    state: latest
  become: yes

- name: Ensure docker compose is installed
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "u=rwx,g=rx,o=rx"
  become: yes

- name: Ensure docker compose completion is installed
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/1.21.2/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    mode: "u=rw,g=r,o=r"
  become: yes

