---
- name: Add the docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: '{{ ansible_distribution_release }}'
    components: stable
    architectures: amd64
    signed_by: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: Ensure docker is installed
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - containerd.io
    state: latest
    update_cache: true
  become: true

- name: Install the docker prune service
  ansible.builtin.copy:
    src: docker-prune.service
    dest: /etc/systemd/system/docker-prune.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Enable the docker prune service on boot
  ansible.builtin.systemd_service:
    name: docker-prune.service
    enabled: true
    daemon_reload: true
  become: true
