---
- name: Install vim
  apt:
    name: vim-gtk
    state: latest
  become: yes

- name: Install software dependencies for what we use with vim
  apt:
    name:
      - silversearcher-ag
      - build-essential
      - cmake
      - python
      - python-dev
    state: latest
  become: yes

- name: Create .vim directory
  file:
    path: ~/.vim
    state: directory

- name: Create autoload directory
  file:
    path: ~/.vim/autoload/
    state: directory

- name: Setup .vimrc
  copy:
    src: files/vimrc
    dest: ~/.vimrc

- name: Setup vim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Copy snippets
  copy:
    src: files/ultisnips/
    dest: ~/.vim/

- name: Install node dependencies
  npm:
    global: yes
    name: "{{ item }}"
  become: yes
  with_items:
    - jsonlint
    - js-yaml
    - prettier
    - eslint
    - eslint-plugin-react
    - eslint-plugin-prettier
    - eslint-config-prettier
