---
- name: Install autojump
  ansible.builtin.apt:
    name: autojump
    state: latest
  become: true

- name: Install the autojump initializer
  ansible.builtin.copy:
    content: ". /usr/share/autojump/autojump.sh"
    dest: ~/.bash.d/autojump.bash
    force: true
    mode: '0644'
