---
- name: Install alacritty
  apt:
    name: alacritty
    state: latest
  become: yes

- name: Ensure alacritty config exists
  file:
      path: ~/.config/alacritty
      state: directory

- name: Setup terminal config
  copy:
    src: files/alacritty.toml
    dest: ~/.config/alacritty/alacritty.toml

- name: Setup dark theme
  copy:
    src: files/gruvbox_dark.toml
    dest: ~/.config/alacritty/gruvbox_dark.toml

- name: Setup light theme
  copy:
    src: files/gruvbox_light.toml
    dest: ~/.config/alacritty/gruvbox_light.toml

