---
- name: Install alacritty
  ansible.builtin.apt:
    name: alacritty
    state: latest
  become: true

- name: Ensure alacritty config exists
  ansible.builtin.file:
    path: ~/.config/alacritty
    state: directory
    mode: '0755'

- name: Setup terminal config
  ansible.builtin.copy:
    src: files/alacritty.toml
    dest: ~/.config/alacritty/alacritty.toml
    mode: '0644'

- name: Setup dark theme
  ansible.builtin.copy:
    src: files/gruvbox_dark.toml
    dest: ~/.config/alacritty/gruvbox_dark.toml
    mode: '0644'

- name: Setup light theme
  ansible.builtin.copy:
    src: files/gruvbox_light.toml
    dest: ~/.config/alacritty/gruvbox_light.toml
    mode: '0644'
