---
- name: Install alacritty
  apt:
    name: alacritty
    state: latest
  become: yes

- name: Setup terminal config
  copy:
    src: files/alacritty.yml
    dest: ~/.config/alacritty/alacritty.yml

- name: Setup dark theme
  copy:
    src: files/gruvbox_dark.yaml
    dest: ~/.config/alacritty/gruvbox_dark.yaml

- name: Setup light theme
  copy:
    src: files/gruvbox_light.yaml
    dest: ~/.config/alacritty/gruvbox_light.yaml

